[package]
name = "shared"
version = "0.1.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
derivative = "*"